add missing argument to call
knit.c:374:13: warning: too few arguments in call to 'kntclrlast'
  374 |         kntclrlast();
      |         ~~~~~~~~~~ ^